version: "3"

services:
  composer:
    image: composer:latest
    command: [ "composer", "install" ]
    volumes:
      - .:/app

  nginx:
    container_name: contacts-nginx
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    volumes:
      - .:/app
    ports:
      - "443:443"
    restart: unless-stopped

  php:
    container_name: contacts-php
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    volumes:
      - .:/app
    expose:
      - "9000"
    working_dir: /app
    restart: unless-stopped
